### ISSUE TITLE
Qt 4 still used as default

### ISSUE THREAD

**Issue by pmattern** [lxde/compton-conf#16]
ComptonConf code is still considering Qt 4 the default version to be used.

This issue is exactly the counterpart of lxde/obconf-qt#8 regarding ObConf-Qt, thus I'm not repeating all that stuff here.
The only significant difference is that CMake was invoked as `cmake CMakeLists.txt` when compiling ComptonConf according to the [Build instructions](https://github.com/lxde/compton-conf#build-instructions) but the (error) messages were the same.

**Comment by agaida** [comment]
+1 for switching the default to Qt5 - it would be a sensible approach to have Qt4 builds available, because there are no LXQt dependencies - compton-conf is useful for pure Qt environments.

**Comment by agaida** [comment]
done with #80ebe77d
