### ISSUE TITLE
Arch linux build error

### ISSUE THREAD

**Issue by Ygarr** [lxde/compton-conf#57]
##### Expected Behavior

build succeful

##### Current Behavior
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:8 (find_package):
  Could not find a configuration file for package "lxqt-build-tools" that is
  compatible with requested version "0.4.0".

  The following configuration files were considered but not accepted:

    /usr/share/cmake/lxqt-build-tools/lxqt-build-tools-config.cmake, version: 0.3.2

-- Configuring incomplete, errors occurred!
See also "/tmp/yaourt-tmp-kdiv/aur-compton-conf-git/src/build/CMakeFiles/CMakeOutput.log".

##### Possible Solution
add/find smth dependencies

##### Steps to Reproduce (for bugs)

1. yaourt compton-conf-git
2. 
3. 
4. 

##### Context
As a compton alternative to "paranoia" tool in Antergos

##### System Information

* Distribution & Version: 
* Kernel: 4.13.11-1-ARCH
* Qt Version: 5.9.2-1
* libqtxgd Version:cannot find installed
* lxqt-build-tools Version: lxqt-build-tools-git and lxqt-build-tools are in conflict. Remove lxqt-build-tools? 
* Package version: 0.4.0-5 and 0.3.2-1 both by seq one by one

**Comment by palinek** [comment]
The build process fails correctly as it doesn't find suitable lxqt-build-tools.

Closing as downstream issue..
